export const states = {
  GA: {
    name: "Georgia",
    yearsWorked: 10,
    projectsCompleted: 200,
    squareFtFlooring: 250000,
    commercialProjects: 100,
    residentialProjects: 100,
  },
  MT: {
    name: "Montana",
    yearsWorked: 4,
    projectsCompleted: 80,
    squareFtFlooring: 95000,
    commercialProjects: 20,
    residentialProjects: 60,
  },
  NV: {
    name: "Nevada",
    yearsWorked: 6,
    projectsCompleted: 120,
    squareFtFlooring: 140000,
    commercialProjects: 60,
    residentialProjects: 60,
  },
  AZ: {
    name: "Arizona",
    yearsWorked: 7,
    projectsCompleted: 150,
    squareFtFlooring: 170000,
    commercialProjects: 75,
    residentialProjects: 75,
  },
  TX: {
    name: "Texas",
    yearsWorked: 12,
    projectsCompleted: 300,
    squareFtFlooring: 400000,
    commercialProjects: 150,
    residentialProjects: 150,
  },
  LA: {
    name: "Louisiana",
    yearsWorked: 8,
    projectsCompleted: 180,
    squareFtFlooring: 210000,
    commercialProjects: 90,
    residentialProjects: 90,
  },
  MS: {
    name: "Mississippi",
    yearsWorked: 5,
    projectsCompleted: 100,
    squareFtFlooring: 120000,
    commercialProjects: 40,
    residentialProjects: 60,
  },
  AL: {
    name: "Alabama",
    yearsWorked: 6,
    projectsCompleted: 110,
    squareFtFlooring: 130000,
    commercialProjects: 50,
    residentialProjects: 60,
  },
  FL: {
    name: "Florida",
    yearsWorked: 15,
    projectsCompleted: 350,
    squareFtFlooring: 450000,
    commercialProjects: 200,
    residentialProjects: 150,
  },
  TN: {
    name: "Tennessee",
    yearsWorked: 9,
    projectsCompleted: 190,
    squareFtFlooring: 220000,
    commercialProjects: 95,
    residentialProjects: 95,
  },
  KY: {
    name: "Kentucky",
    yearsWorked: 7,
    projectsCompleted: 130,
    squareFtFlooring: 160000,
    commercialProjects: 60,
    residentialProjects: 70,
  },
  IN: {
    name: "Indiana",
    yearsWorked: 8,
    projectsCompleted: 140,
    squareFtFlooring: 180000,
    commercialProjects: 70,
    residentialProjects: 70,
  },
  VA: {
    name: "Virginia",
    yearsWorked: 9,
    projectsCompleted: 200,
    squareFtFlooring: 240000,
    commercialProjects: 100,
    residentialProjects: 100,
  },
  NC: {
    name: "North Carolina",
    yearsWorked: 10,
    projectsCompleted: 210,
    squareFtFlooring: 260000,
    commercialProjects: 120,
    residentialProjects: 90,
  },
  SC: {
    name: "South Carolina",
    yearsWorked: 8,
    projectsCompleted: 170,
    squareFtFlooring: 200000,
    commercialProjects: 80,
    residentialProjects: 90,
  },
};
